load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_hair_segmentation_aar",
    calculators = ["//mediapipe/graphs/hair_segmentation:mobile_calculators"],
)
